services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Secret5555
      MYSQL_DATABASE: wordpress
    volumes:
      - my-datavolume:/var/lib/mysql
  wordpress:
    build: .
    ports:
      - "8086:8000"
    user: "www-data:www-data"
    volumes:
      - my-contentvolume:/var/local/wordpress/wp-content
volumes:
  my-datavolume:
  my-contentvolume: