services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Secret5555
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
    volumes:
      - my-datavolume:/var/lib/mysql
  wordpress:
    build: .
    ports:
      - "8000:8000"
    user: "www-data:www-data"
    volumes:
      - my-contentvolume:/var/local/wordpress/wp-content
    environment:
      # OTel auto instrumentation config
      # https://opentelemetry.io/docs/instrumentation/php/automatic/#installation
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_SERVICE_NAME=my-wordpress-installation
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
volumes:
  my-datavolume:
  my-contentvolume:
